apiVersion: v2
name: steamcmd-proton-chart
description: Deploy a Windows SteamCMD game server under Proton and Hard Boiled Yolks control.
type: application
version: 1.0.0
appVersion: steamcmd_proton
dependencies:
  - name: hard-boiled-yolks
    alias: hby
    version: 1.0.0
    repository: file://../hard-boiled-yolks
