apiVersion: v2
name: steamcmd-chart
description: Deploy a native Linux SteamCMD game server with Hard Boiled Yolks control.
type: application
version: 1.0.0
appVersion: steamcmd
dependencies:
  - name: hard-boiled-yolks
    alias: hby
    version: 1.0.0
    repository: file://../hard-boiled-yolks
