apiVersion: v2
name: minecraft-modrinth-fabric
description: Deploy a Fabric Minecraft server bootstrapped from a Modrinth .mrpack.
type: application
version: 0.1.3
appVersion: fabric
keywords:
  - minecraft
  - fabric
  - modrinth
  - mrpack
home: https://github.com/NickMagic25/hard-boiled-yolks
maintainers:
  - name: Nick Majkic
