hby:
  image:
    repository: hard-boiled-yolks
    tag: java_25
    pullPolicy: IfNotPresent
  ports:
    - name: minecraft
      containerPort: 25565
      servicePort: 25565
      protocol: TCP
  persistence:
    mountPath: /home/container
    size: 10Gi

installerImage:
  repository: hard-boiled-yolks
  tag: installer_modrinth
  pullPolicy: IfNotPresent

minecraft:
  eula: false
  serverJarFile: server.jar
  startup: 'java {{JAVA_OPTS}} -jar {{SERVER_JARFILE}} {{MINECRAFT_ARGS}}'
  javaOpts: -Xms128M -Xmx4G
  args: nogui
  extraJars: []

modrinth:
  apiBase: https://api.modrinth.com/v2
  projectId: ""
  versionId: ""
  versionNumber: ""
  userAgent: minecraft-modrinth-fabric-chart/1.0
  installPolicy: IfChanged
  fabricInstallerVersion: "1.0.3"
  auth:
    enabled: true
    scheme: raw
    existingSecret: ""
    secretKey: MODRINTH_TOKEN
  pack:
    url: ""
    filename: modrinth.mrpack
    sha512: ""
