{{- $ctx := dict "root" . "hby" .Values.hby -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hby.fullname" $ctx }}-installer
  labels:
    {{- include "hby.labels" $ctx | nindent 4 }}
data:
  install-modrinth-pack.sh: |-
{{ .Files.Get "scripts/install-modrinth-pack.sh" | indent 4 }}
