{{- if .Values.gatewayIngress.enabled -}}
{{- $root := . -}}
{{- range $index, $route := .Values.gatewayIngress.data }}
{{- $kind := required "gatewayIngress.data[].kind is required" $route.kind -}}
{{- $name := default (include "minecraft-modrinth-fabric.fullname" $root) $route.name -}}
{{- $port := default $root.Values.service.port $route.port -}}
{{- $serviceName := include "minecraft-modrinth-fabric.fullname" $root -}}
{{- $hostnames := list -}}
{{- if $route.hostnames -}}
{{- $hostnames = $route.hostnames -}}
{{- else if $route.hostname -}}
{{- $hostnames = list $route.hostname -}}
{{- end -}}
---
apiVersion: {{ default (ternary "gateway.networking.k8s.io/v1alpha2" "gateway.networking.k8s.io/v1" (eq $kind "TCPRoute")) $route.apiVersion }}
kind: {{ $kind }}
metadata:
  name: {{ $name }}
  namespace: {{ default $root.Release.Namespace $route.namespace }}
  labels:
    {{- include "minecraft-modrinth-fabric.labels" $root | nindent 4 }}
    {{- with $route.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if or $route.externalDNS $route.annotations }}
  annotations:
    {{- if and $route.externalDNS $hostnames }}
    external-dns.alpha.kubernetes.io/hostname: {{ join "," $hostnames | quote }}
    {{- end }}
    {{- with $route.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  {{- if and (eq $kind "HTTPRoute") $hostnames }}
  hostnames:
    {{- toYaml $hostnames | nindent 4 }}
  {{- end }}
  parentRefs:
    {{- toYaml (required "gatewayIngress.data[].spec.parentRefs is required" $route.spec.parentRefs) | nindent 4 }}
  rules:
    {{- if $route.spec.rules }}
    {{- range $rule := $route.spec.rules }}
    {{- if and (eq $kind "HTTPRoute") $rule.matches }}
    - matches:
        {{- toYaml $rule.matches | nindent 8 }}
      {{- with $rule.filters }}
      filters:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if and (hasKey $rule "backendRefs") $rule.backendRefs }}
      backendRefs:
        {{- toYaml $rule.backendRefs | nindent 8 }}
      {{- else if not $rule.filters }}
      backendRefs:
        - name: {{ $serviceName }}
          port: {{ $port }}
      {{- end }}
    {{- else if $rule.filters }}
    - filters:
        {{- toYaml $rule.filters | nindent 8 }}
      {{- if and (hasKey $rule "backendRefs") $rule.backendRefs }}
      backendRefs:
        {{- toYaml $rule.backendRefs | nindent 8 }}
      {{- end }}
    {{- else if and (hasKey $rule "backendRefs") $rule.backendRefs }}
    - backendRefs:
        {{- toYaml $rule.backendRefs | nindent 8 }}
    {{- else }}
    - backendRefs:
        - name: {{ $serviceName }}
          port: {{ $port }}
    {{- end }}
    {{- end }}
    {{- else }}
    - backendRefs:
        - name: {{ $serviceName }}
          port: {{ $port }}
    {{- end }}
{{ end }}
{{- end }}
