{{- if and .Values.modrinth.auth.enabled .Values.modrinth.auth.createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minecraft-modrinth-fabric.tokenSecretName" . }}
  labels:
    {{- include "minecraft-modrinth-fabric.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.modrinth.auth.secretKey }}: {{ required "modrinth.auth.token is required when modrinth.auth.createSecret=true" .Values.modrinth.auth.token | quote }}
{{- end }}

