apiVersion: v1
kind: Service
metadata:
  name: {{ include "minecraft-modrinth-fabric.fullname" . }}
  labels:
    {{- include "minecraft-modrinth-fabric.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: minecraft
      port: {{ .Values.service.port }}
      targetPort: minecraft
      protocol: TCP
    {{- with .Values.service.extraPorts }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  selector:
    {{- include "minecraft-modrinth-fabric.selectorLabels" . | nindent 4 }}
